/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModel.Vi;
import Service.Implement.ViServiceImplement;
import Service.Interface.ViServiceInterface;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLyViFrame extends javax.swing.JFrame {

    private ViServiceInterface viServiceInterface;

    /**
     * Creates new form QuanLyViFrame
     */
    public QuanLyViFrame() {
        initComponents();
        setLocationRelativeTo(null);
        viServiceInterface = new ViServiceImplement();
        loadtableVI();
    }

    public void loadtableVI() {
        DefaultTableModel tblModel = (DefaultTableModel) tblViSanPham.getModel();
        tblModel.setRowCount(0);
        List<Vi> listVi = viServiceInterface.getAllVi();
        for (Vi vi : listVi) {
            tblModel.addRow(new Object[]{
                vi.getId(),
                vi.getMa(),
                vi.getTen()
            });
        }
    }

    public void DisPlayFromVi() {
        int row = tblViSanPham.getSelectedRow();
        if (row >= 0) {
            txtMaVi.setText((String) tblViSanPham.getValueAt(row, 1));
            txtTenVi.setText((String) tblViSanPham.getValueAt(row, 2));
            txtMaVi.setEditable(false);
        }
    }

    public void clearFromVi() {
        txtMaVi.setText("");
        txtTenVi.setText("");
        txtMaVi.setEditable(false);
    }

    public boolean validateVifrom() {
        String ma = txtMaVi.getText();
        String TenVi = txtTenVi.getText();
        if (ma.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã Không được để trống");
            return false;
        }
        List<Vi> listVi = viServiceInterface.getAllVi();
        for (Vi vi : listVi) {
            if (vi.getMa().equals(ma)) {
                JOptionPane.showMessageDialog(this, "Mã Đã Tồn Tại");
                return false;
            }
        }
        if (TenVi.trim().equals("")) {
            JOptionPane.showMessageDialog(this, " Tên Vị Không được để trống");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaVi = new javax.swing.JTextField();
        txtTenVi = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViSanPham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlVi.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản Lý Vị Sản Phẩm");

        jLabel3.setText("Mã");

        jLabel4.setText("Tên");

        btnThem.setBackground(new java.awt.Color(204, 255, 204));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(204, 255, 204));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 102, 102));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblViSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Mã", "Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViSanPham);

        javax.swing.GroupLayout pnlViLayout = new javax.swing.GroupLayout(pnlVi);
        pnlVi.setLayout(pnlViLayout);
        pnlViLayout.setHorizontalGroup(
            pnlViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViLayout.createSequentialGroup()
                .addGroup(pnlViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(pnlViLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(pnlViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlViLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaVi))
                            .addGroup(pnlViLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenVi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(81, 81, 81)
                        .addGroup(pnlViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)))
                    .addGroup(pnlViLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        pnlViLayout.setVerticalGroup(
            pnlViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlViLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addGroup(pnlViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtTenVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(pnlViLayout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(pnlVi, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblViSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViSanPhamMouseClicked
        // TODO add your handling code here:
        DisPlayFromVi();
    }//GEN-LAST:event_tblViSanPhamMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (validateVifrom() == true) {
            Vi vi = new Vi();
            vi.setMa(txtMaVi.getText());
            vi.setTen(txtTenVi.getText());
            try {
                viServiceInterface.addVi(vi);
                loadtableVI();
                clearFromVi();
                JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int row = tblViSanPham.getSelectedRow();
        if (row >= 0) {
            Vi vi = new Vi();
            vi.setMa(txtMaVi.getText());
            vi.setTen(txtTenVi.getText());
            try {
                viServiceInterface.updateVi(vi);
                loadtableVI();
                clearFromVi();
                JOptionPane.showMessageDialog(this, "Sửa Thành Công");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Chọn mục cần sửa");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tblViSanPham.getSelectedRow();
        if (row >= 0) {
            Vi vi = new Vi();
            vi.setMa(txtMaVi.getText());
            try {
                viServiceInterface.deleteVi(vi);
                loadtableVI();
                clearFromVi();
                JOptionPane.showMessageDialog(this, "Xóa Thành Công");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Chọn mục cần Xóa");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyViFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyViFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyViFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyViFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyViFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlVi;
    private javax.swing.JTable tblViSanPham;
    private javax.swing.JTextField txtMaVi;
    private javax.swing.JTextField txtTenVi;
    // End of variables declaration//GEN-END:variables
}
